name: flutter_map_marker_cluster
description: A Dart implementation of Leaflet.makercluster for Flutter apps.
  Provides beautiful animated marker clustering functionality for flutter_map.
version: 1.0.1

homepage: https://github.com/lpongetti/flutter_map_marker_cluster

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    git:
      url: https://github.com/pauloricardomsop/flutter_map
  flutter_map_marker_popup:
    git:
      url: https://github.com/pauloricardomsop/flutter_map_marker_popup
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
